# Generated by Django 3.0.7 on 2020-07-24 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
