# Generated by Django 3.0.7 on 2020-07-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedu', '0005_auto_20200724_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reference',
            field=models.URLField(blank=True),
        ),
    ]
