# Generated by Django 3.0.7 on 2020-07-25 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedu', '0006_user_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Programming', 'Programming'), ('UX', 'UX'), ('Finance', 'Finance'), ('Database', 'Database'), ('Art', 'Art'), ('Productivity', 'Productivity')], max_length=48, null=True)),
                ('user_choice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_choices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
