# Generated by Django 3.0.7 on 2020-07-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedu', '0007_choices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choices',
        ),
    ]
