# Generated by Django 3.0.7 on 2020-07-26 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedu', '0010_auto_20200726_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='raters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_rated', to=settings.AUTH_USER_MODEL),
        ),
    ]
