# Generated by Django 3.0.7 on 2020-07-26 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedu', '0011_auto_20200726_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='raters',
        ),
        migrations.AddField(
            model_name='course',
            name='raters',
            field=models.ManyToManyField(related_name='course_rated', to=settings.AUTH_USER_MODEL),
        ),
    ]
