# Generated by Django 3.0.7 on 2020-07-26 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedu', '0012_auto_20200726_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='raters',
            field=models.ManyToManyField(blank=True, related_name='course_rated', to=settings.AUTH_USER_MODEL),
        ),
    ]
