# Generated by Django 3.0.7 on 2020-07-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedu', '0013_auto_20200726_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='raters',
        ),
    ]
