# Generated by Django 3.0.7 on 2020-07-26 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedu', '0014_remove_course_raters'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='raters',
            field=models.ManyToManyField(blank=True, related_name='course_rated', to=settings.AUTH_USER_MODEL),
        ),
    ]
