# Generated by Django 3.0.7 on 2020-07-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedu', '0017_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='course/%Y/%m/%d/'),
        ),
    ]
