# Generated by Django 3.0.7 on 2020-07-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedu', '0022_course_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
