# Generated by Django 3.0.7 on 2020-07-31 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedu', '0024_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
