# Generated by Django 3.0.7 on 2020-07-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedu', '0029_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
