# Generated by Django 3.0.7 on 2020-08-01 04:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedu', '0031_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussion',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='discussion_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
